server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/service-db
    username: username
    password: password
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
  application:
    name: order-service

topic:
  send-order: send-order-event